#!/bin/bash
export BW_IMPLEMENTATION=1

# Gaze
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/mixed_real_synthetic_samesize -n 5000
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended -n 10000
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended_large -n 100000
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrow -n 5000 --filter_gz_radius 25
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrower -n 5000 --filter_gz_radius 19
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_wide -n 5000 --filter_gz_deadzone 25
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/complement_wide -n 5000 --filter_gz_deadzone 25
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/complement_wider -n 5000 --filter_gz_deadzone 19
python scripts/synthesize_trainingdata.py -m gh119_ivgaze_eyes_balanced_trainsubjects_cl07_gz_ada_fromscratch --batch 8 --res 64 --poses /mnt/d/IVGazeDataset/scripts/pose_eyes.json --classifier models/classifier/vit8_gz_iveyes --labels gaze --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/complement_narrow -n 5000 --filter_gz_radius 25
