#!/bin/bash
export BW_IMPLEMENTATION=1

# Facial Hair
# Already done X
#python scripts/synthesize_trainingdata.py -m gh110_fnir_balanced_trainsubjects_cl05_fh_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_fh_fnir_old --labels facial_hair --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/mixed_real_synthetic_samesize -n 1250
#python scripts/synthesize_trainingdata.py -m gh110_fnir_balanced_trainsubjects_cl05_fh_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_fh_fnir_old --labels facial_hair --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/full_real_synthetic_extended -n 2500
#python scripts/synthesize_trainingdata.py -m gh110_fnir_balanced_trainsubjects_cl05_fh_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_fh_fnir_old --labels facial_hair --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/full_real_synthetic_extended_large -n 25000
#python scripts/synthesize_trainingdata.py -m gh110_fnir_balanced_trainsubjects_cl05_fh_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_fh_fnir_old --labels facial_hair --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/synthetic_fh0 -n 1250 --filter_fh 0
#python scripts/synthesize_trainingdata.py -m gh110_fnir_balanced_trainsubjects_cl05_fh_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_fh_fnir_old --labels facial_hair --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/synthetic_fh1 -n 1250 --filter_fh 1
#python scripts/synthesize_trainingdata.py -m gh110_fnir_balanced_trainsubjects_cl05_fh_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_fh_fnir_old --labels facial_hair --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/full_synthetic -n 2500

# Glasses
# TODO: run
python scripts/synthesize_trainingdata.py -m gh120_fnir_balanced_trainsubjects_cl03_gl_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gl_fnir --labels glasses --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/mixed_real_synthetic_samesize -n 1250
python scripts/synthesize_trainingdata.py -m gh120_fnir_balanced_trainsubjects_cl03_gl_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gl_fnir --labels glasses --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/full_real_synthetic_extended -n 2500
python scripts/synthesize_trainingdata.py -m gh120_fnir_balanced_trainsubjects_cl03_gl_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gl_fnir --labels glasses --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/full_real_synthetic_extended_large -n 25000
python scripts/synthesize_trainingdata.py -m gh120_fnir_balanced_trainsubjects_cl03_gl_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gl_fnir --labels glasses --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/synthetic_gl0 -n 1250 --filter_gl 0
python scripts/synthesize_trainingdata.py -m gh120_fnir_balanced_trainsubjects_cl03_gl_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gl_fnir --labels glasses --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/synthetic_gl1 -n 1250 --filter_gl 1
python scripts/synthesize_trainingdata.py -m gh120_fnir_balanced_trainsubjects_cl03_gl_ada_attrskip_resume --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gl_fnir --labels glasses --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/full_synthetic -n 2500

# Bright Pupil
# TODO: add model
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_bp_fnir --labels bright_pupil --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/mixed_real_synthetic_samesize -n 1250
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_bp_fnir --labels bright_pupil --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_real_synthetic_extended -n 2500
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_bp_fnir --labels bright_pupil --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_real_synthetic_extended_large -n 25000
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_bp_fnir --labels bright_pupil --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/synthetic_bp0 -n 1250 --filter_bp 0
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_bp_fnir --labels bright_pupil --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/synthetic_bp1 -n 1250 --filter_bp 1
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_bp_fnir --labels bright_pupil --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_synthetic -n 2500

# Eye Open
# TODO: add model
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_eo_fnir --labels eye_open --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/mixed_real_synthetic_samesize -n 2500
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_eo_fnir --labels eye_open --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_real_synthetic_extended -n 5000
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_eo_fnir --labels eye_open --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_real_synthetic_extended_large -n 50000
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_eo_fnir --labels eye_open --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/synthetic_closed -n 2500 --filter_eo_max 0.5
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_eo_fnir --labels eye_open --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/synthetic_open -n 2500 --filter_eo_min 0.5
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_eo_fnir --labels eye_open --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_synthetic -n 5000

# Gaze
# TODO: add model
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/mixed_real_synthetic_samesize -n 2500 --augment_distribution
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended -n 5000 --augment_distribution
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended_large -n 50000 --augment_distribution
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrow -n 2500 --filter_gz_radius 25
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrower -n 2500 --filter_gz_radius 19
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/synthetic_wide -n 2500 --filter_gz_deadzone 25
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/complement_wide -n 2500 --filter_gz_deadzone 25
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/complement_wider -n 2500 --filter_gz_deadzone 19
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/complement_narrow -n 2500 --filter_gz_radius 25
#python scripts/synthesize_trainingdata.py -m gh --batch 8 --res 256 --poses /mnt/g/FacesNIR/scripts/fnir_d3fr_dataset.json --classifier models/classifier/vit16_gz_fnir --labels gaze --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_synthetic -n 5000
