#!/bin/bash
export BW_IMPLEMENTATION=1

#python scripts/synthesize_trainingdata.py -m gh75_enir_resample_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open/synthetic_closed -n 5000 --filter_eo_max 0.5
#python scripts/synthesize_trainingdata.py -m gh75_enir_resample_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open/synthetic_open -n 5000 --filter_eo_min 0.5
#python scripts/synthesize_trainingdata.py -m gh75_enir_resample_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_synthetic -n 10000
#python scripts/synthesize_trainingdata.py -m gh75_enir_resample_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_real_synthetic_extended -n 10000

#python scripts/synthesize_trainingdata.py -m gh77_enir_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/synthetic_closed -n 5000 --filter_eo_max 0.5
#python scripts/synthesize_trainingdata.py -m gh77_enir_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/synthetic_open -n 5000 --filter_eo_min 0.5
#python scripts/synthesize_trainingdata.py -m gh77_enir_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/full_synthetic -n 10000
#python scripts/synthesize_trainingdata.py -m gh77_enir_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 8 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/full_real_synthetic_extended -n 10000

python scripts/synthesize_trainingdata.py -m gh71_enir_balanced_trainsubjects_cl07_bp_plane_attrskip_fromscratch --batch 16 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_bp --labels bright_pupil --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_real_synthetic_extended_large -n 50000
python scripts/synthesize_trainingdata.py -m gh75_enir_resample_balanced_trainsubjects_ada_cl075_eo_plane_attrskip_fromscratch --batch 16 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_eo --labels eye_open --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_real_synthetic_extended_large -n 100000
python scripts/synthesize_trainingdata.py -m gh76_enir_resample_balanced_trainsubjects_ada_cl075_gz_plane_attrskip_fromscratch --batch 16 --poses /mnt/g/EyesNIR/resample/processings/eg3d_pose/dataset_enir.json --classifier models/classifier/vit16_gz --labels gaze --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended_large -n 100000
