#!/bin/bash
export BW_IMPLEMENTATION=1

# Gaze
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/mixed_real_synthetic_samesize/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_mixed_real_synthetic_samesize_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real_synthetic_extended_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended_large/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real_synthetic_extended_large_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrow/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_narrow_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrower/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_narrower_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_wide/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_wide_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/real_complement_wide/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_wide_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/real_complement_wider/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_wider_gh119
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/real_complement_narrow/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_narrow_gh119
python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_synthetic/gh119 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_synthetic_gh119
