#!/bin/bash
export BW_IMPLEMENTATION=1

# Gaze
# TODO: insert model number
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/mixed_real_synthetic_samesize/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_mixed_real_synthetic_samesize_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real_synthetic_extended_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended_large/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real_synthetic_extended_large_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrow/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_narrow_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrower/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_narrower_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/synthetic_wide/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_wide_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/real_complement_wide/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_wide_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/real_complement_wider/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_wider_gh
#python scripts/train_classifier.py --img_res 64 --dataset /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/trainsets/gaze/real_complement_narrow/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/d/IVGazeDataset/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_narrow_gh
