#!/bin/bash
export BW_IMPLEMENTATION=1

# Facial Hair
# Already done X
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_full_real
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/mixed_real_synthetic_samesize/gh110 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_mixed_real_synthetic_samesize_gh110
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/full_real_synthetic_extended/gh110 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_full_real_synthetic_extended_gh110
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/full_real_synthetic_extended_large/gh110 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_full_real_synthetic_extended_large_gh110
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/synthetic_fh0/gh110 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_synthetic_fh0_gh110
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/synthetic_fh1/gh110 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_synthetic_fh1_gh110
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/real_complement_fh0 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_real_complement_fh0
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/real_complement_fh1 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_real_complement_fh1
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/facial_hair/full_synthetic/gh110 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels facial_hair --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/facial_hair/vit16_fh_full_synthetic_gh110

# Glasses
# Already done X
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_full_real
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/mixed_real_synthetic_samesize/gh120 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_mixed_real_synthetic_samesize_gh120
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/full_real_synthetic_extended/gh120 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_full_real_synthetic_extended_gh120
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/full_real_synthetic_extended_large/gh120 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_full_real_synthetic_extended_large_gh120
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/synthetic_gl0/gh120 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_synthetic_gl0_gh120
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/synthetic_gl1/gh120 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_synthetic_gl1_gh120
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/real_complement_gl0 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 4 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_real_complement_gl0
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/real_complement_gl1 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 4 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_real_complement_gl1
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/glasses/full_synthetic/gh120 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels glasses --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/glasses/vit16_gl_full_synthetic_gh120

# Bright Pupil
# TODO: insert model number
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_full_real
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/mixed_real_synthetic_samesize/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_mixed_real_synthetic_samesize_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_real_synthetic_extended/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_full_real_synthetic_extended_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_real_synthetic_extended_large/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_full_real_synthetic_extended_large_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/synthetic_bp0/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_synthetic_bp0_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/synthetic_bp1/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_synthetic_bp1_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/real_complement_bp0 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 4 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_real_complement_bp0
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/real_complement_bp1 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 4 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_real_complement_bp1
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/bright_pupil/full_synthetic/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels bright_pupil --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/bright_pupil/vit16_bp_full_synthetic_gh

# Eye Open
# TODO: insert model number
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_full_real
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/mixed_real_synthetic_samesize/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_mixed_real_synthetic_samesize_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_real_synthetic_extended/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_full_real_synthetic_extended_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_real_synthetic_extended_large/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_full_real_synthetic_extended_large_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/synthetic_closed/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_synthetic_closed_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/synthetic_open/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_synthetic_open_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/real_complement_closed --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_real_complement_closed
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/real_complement_open --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_real_complement_open
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/eye_open/full_synthetic/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/eye_open/vit16_eo_full_synthetic_gh

# Gaze
# TODO: insert model number
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/mixed_real_synthetic_samesize/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_mixed_real_synthetic_samesize_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real_synthetic_extended_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_real_synthetic_extended_large/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_real_synthetic_extended_large_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrow/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_narrow_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/synthetic_narrower/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_narrower_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/synthetic_wide/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_synthetic_wide_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/real_complement_wide/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_wide_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/real_complement_wider/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_wider_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/real_complement_narrow/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_real_complement_narrow_gh
#python scripts/train_classifier.py --img_res 256 --dataset /mnt/g/FacesNIR/synthetic_augmented_classifiers/trainsets/gaze/full_synthetic/gh --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels gaze --flip_aug --dst /mnt/g/FacesNIR/synthetic_augmented_classifiers/models/gaze/vit16_gz_full_synthetic_gh
