#!/bin/bash
export BW_IMPLEMENTATION=1

python scripts/train_classifier.py --dataset /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/full_synthetic/gh77 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/models/eye_open_nonresample/vit16_eo_full_synthetic_gh77
python scripts/train_classifier.py --dataset /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/synthetic_open/gh77 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/models/eye_open_nonresample/vit16_eo_synthetic_open_gh77
python scripts/train_classifier.py --dataset /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/synthetic_closed/gh77 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/models/eye_open_nonresample/vit16_eo_synthetic_closed_gh77
python scripts/train_classifier.py --dataset /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/full_real_synthetic_extended/gh77 --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/models/eye_open_nonresample/vit16_eo_full_real_synthetic_extended_gh77
python scripts/train_classifier.py --dataset /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/full_real --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/models/eye_open_nonresample/vit16_eo_full_real
python scripts/train_classifier.py --dataset /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/real_complement_open --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/models/eye_open_nonresample/vit16_eo_real_complement_open
python scripts/train_classifier.py --dataset /mnt/g/EyesNIR/synthetic_augmented_classifiers/trainsets/eye_open_nonresample/real_complement_closed --model vit --vit_mlp_dim 1024 --vit_heads 8 --epochs 100 --labels eye_open --flip_aug --dst /mnt/g/EyesNIR/synthetic_augmented_classifiers/models/eye_open_nonresample/vit16_eo_real_complement_closed
